import type { Metadata } from "next";
import { Poppins} from "next/font/google";
import "./globals.css";
import Head from "next/head";


const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Envirocare Labs | Personality Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="min-h-screen">
      <Head>
        <link rel="icon" type="image/png" href="/favicon.png"/>
      </Head>
      <body
        className={`${poppins.variable} antialiased font-poppins h-full grainy`}
      >
        {children}
      </body>
    </html>
  );
}
